services:
  persona-engine-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona-engine-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    networks:
      - persona_network
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - REPOSITORY_TYPE=postgres
      - DB_URI=postgresql://postgres:postgres@db:5432/persona_db
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=persona_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - persona_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  persona_network:
    external: true

volumes:
  pgdata:
